sudo: required
services:
 - docker

before_install:
 - docker build -t steviewu/react-test -f ./client/Dockerfile.dev ./client

script:
 - docker run -e CI=true USERNAME/react-test npm test

after_success:
 - docker build -t steviewu/multi-client ./client
 - docker build -t steviewu/multi-nginx ./nginx
 - docker build -t steviewu/multi-server ./server
 - docker build -t steviewu/multi-worker ./worker
 #login to the docker CLI
 - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
 #Take those images and push them to docker hub
 - docker push steviewu/multi-client
 - docker push steviewu/multi-nginx
 - docker push steviewu/multi-server
 - docker push steviewu/multi-worker
